# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.
"""Validate the AWS pack metadata and plugin-discoverable skill layout."""

from __future__ import annotations

import json
from pathlib import Path

REPO_ROOT = Path(__file__).parent.parent

REQUIRED_DIRS = [
    "skills/sdlc-aws-deployment",
    "skills/sdlc-dynamodb-repository",
    "skills/sdlc-s3-storage",
]

PLUGIN_PACK_JSON = REPO_ROOT / "packs/aws/pack.json"
PLUGIN_JSON = REPO_ROOT / "plugin.json"


class TestDirectoryStructure:
    """Verify that AWS skills are immediate plugin skill directories."""

    def test_aws_skill_directories_exist(self):
        """Ensure every AWS skill is discoverable by current clients."""
        for relative_path in REQUIRED_DIRS:
            path = REPO_ROOT / relative_path
            assert path.is_dir(), f"Directory missing: {path}"
            assert (path / "SKILL.md").is_file(), f"Skill file missing: {path / 'SKILL.md'}"


class TestPluginPackJson:
    """Verify the AWS cloud pack metadata."""

    def test_pack_json_exists(self):
        assert PLUGIN_PACK_JSON.exists(), f"File missing: {PLUGIN_PACK_JSON}"

    def test_pack_json_is_valid_json(self):
        with open(PLUGIN_PACK_JSON) as f:
            data = json.load(f)  # raises if invalid JSON
        assert isinstance(data, dict)

    def test_pack_json_has_name_aws(self):
        with open(PLUGIN_PACK_JSON) as f:
            data = json.load(f)
        assert data["name"] == "aws"

    def test_pack_json_has_display_name(self):
        with open(PLUGIN_PACK_JSON) as f:
            data = json.load(f)
        assert data["displayName"] == "AWS Cloud Pack"

    def test_pack_json_has_version(self):
        with open(PLUGIN_PACK_JSON) as f:
            data = json.load(f)
        assert data["version"] == "1.0.0"

    def test_pack_json_has_cloud_aws(self):
        with open(PLUGIN_PACK_JSON) as f:
            data = json.load(f)
        assert data["cloud"] == "aws"

    def test_pack_json_has_agents(self):
        with open(PLUGIN_PACK_JSON) as f:
            data = json.load(f)
        assert "agents" in data
        agents = data["agents"]
        # deployer is owned by the core pack and inherited here (ADR-0001, decision A)
        assert agents["deployer"] == "deployer.agent.md"
        # pack-local agents use pack-relative paths (Phase 2 layout)
        assert agents["complianceReviewer"] == "agents/aws-compliance-reviewer.agent.md"

    def test_pack_json_agent_files_exist(self):
        """Every agent file referenced by the pack must exist on disk."""
        with open(PLUGIN_PACK_JSON) as f:
            data = json.load(f)
        agents = data["agents"]
        assert set(agents) == {"deployer", "complianceReviewer"}
        # Inherited core agents resolve against the canonical flat agent dirs.
        for agent_dir in ("com.github.copilot/agents", ".github/agents"):
            path = REPO_ROOT / agent_dir / agents["deployer"]
            assert path.is_file(), f"Pack agent missing: deployer -> {path}"
        # Pack-local agents live under packs/aws/agents/; the flat copy is
        # generated by tools/assemble_flat_layout.py (Phase 3).
        pack_agent = REPO_ROOT / "packs" / "aws" / agents["complianceReviewer"]
        assert pack_agent.is_file(), f"Pack agent missing: {pack_agent}"
        flat_agent = REPO_ROOT / "com.github.copilot" / "agents" / pack_agent.name
        assert flat_agent.is_file(), f"Flat mirror missing: {flat_agent}"
        assert pack_agent.read_bytes() == flat_agent.read_bytes(), (
            f"Pack-local agent diverged from flat mirror: {pack_agent}"
        )
        for ref in data.get("reviewers", []):
            path = REPO_ROOT / "packs" / "aws" / ref
            assert path.is_file(), f"Pack reviewer missing: {path}"

    def test_pack_json_has_skills(self):
        with open(PLUGIN_PACK_JSON) as f:
            data = json.load(f)
        assert "skills" in data
        skills = data["skills"]
        # Pack-local skills use pack-relative paths (Phase 2 layout).
        assert "skills/sdlc-aws-deployment" in skills
        assert "skills/sdlc-dynamodb-repository" in skills
        assert "skills/sdlc-s3-storage" in skills

    def test_pack_json_has_mcp_servers(self):
        with open(PLUGIN_PACK_JSON) as f:
            data = json.load(f)
        assert data["mcpServers"] == "mcp-servers.json"

    def test_pack_mcp_servers_file_exists_and_valid(self):
        """The mcpServers file referenced by the pack must exist and define AWS servers."""
        with open(PLUGIN_PACK_JSON) as f:
            data = json.load(f)
        mcp_path = REPO_ROOT / "packs/aws" / data["mcpServers"]
        assert mcp_path.is_file(), f"File missing: {mcp_path}"
        with open(mcp_path) as f:
            mcp = json.load(f)  # raises if invalid JSON
        servers = mcp.get("servers", {})
        assert "aws-cdk" in servers, "aws-cdk server missing from pack mcp-servers.json"
        assert "aws-docs" in servers, "aws-docs server missing from pack mcp-servers.json"

    def test_pack_skills_all_exist(self):
        """Every skill listed in the pack must exist under packs/aws/skills/."""
        with open(PLUGIN_PACK_JSON) as f:
            data = json.load(f)
        assert set(data["skills"]) == {
            "skills/sdlc-aws-deployment",
            "skills/sdlc-dynamodb-repository",
            "skills/sdlc-s3-storage",
        }
        for skill in data["skills"]:
            name = skill.removeprefix("skills/")
            pack_skill = REPO_ROOT / "packs" / "aws" / "skills" / name / "SKILL.md"
            assert pack_skill.is_file(), f"Pack skill missing: {pack_skill}"
            # The root skills/ copy is generated by tools/assemble_flat_layout.py.
            flat_skill = REPO_ROOT / "skills" / name / "SKILL.md"
            assert flat_skill.is_file(), f"Flat skill mirror missing: {flat_skill}"

    def test_pack_json_has_reviewers(self):
        with open(PLUGIN_PACK_JSON) as f:
            data = json.load(f)
        assert "reviewers" in data
        reviewers = data["reviewers"]
        assert "agents/aws-compliance-reviewer.agent.md" in reviewers
