#!/usr/bin/env python3
"""Assemble the root flat layout from packs/*/ (ADR-0001 Phase 3).

``packs/<name>/`` is the single source of truth. This script derives the
compatibility flat layout that Agent Plugins / Copilot clients consume:

  com.github.copilot/agents/  <- union of every pack's resolved agents
  .github/agents/             <- same union (mirror)
  skills/                     <- union of every pack's resolved skills

Each assembled directory gets a ``.pack-generated`` marker: do not edit the
flat layout by hand -- change the pack source and re-run this script.

Usage:
  python3 tools/assemble_flat_layout.py          # regenerate the flat layout
  python3 tools/assemble_flat_layout.py --check  # CI: fail if the checked-in
                                                 # flat layout differs from
                                                 # what the packs produce

Reference resolution (same as tools/check_pack_contracts.py):
  agents:  "agents/<file>" -> packs/<name>/agents/<file>   (pack-local)
           "<file>"        -> packs/<name>/agents/<file>, then
                              packs/core/agents/<file>      (inheritance:
                              how cloud packs reuse core agents)
  skills:  "skills/<name>" -> packs/<name>/skills/<name>   (pack-local)
           "<name>"        -> skills/<name>

Two different source files mapping to the same flat name is a conflict and
fails the assembly.
"""

from __future__ import annotations

import argparse
import filecmp
import json
import shutil
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
PACKS_DIR = REPO_ROOT / "packs"
CORE_PACK_DIR = PACKS_DIR / "core"
TEMPLATE_DIR_NAME = "_template"

COPILOT_AGENTS = REPO_ROOT / "com.github.copilot" / "agents"
GITHUB_AGENTS = REPO_ROOT / ".github" / "agents"
SKILLS_DIR = REPO_ROOT / "skills"

MARKER_NAME = ".pack-generated"
MARKER_TEXT = (
    "Generated by tools/assemble_flat_layout.py from packs/*/.\n"
    "Do not edit -- change the pack source instead (ADR-0001).\n"
)

failures: list[str] = []


def fail(message: str) -> None:
    failures.append(message)
    print(f"FAIL: {message}")


def _rel(path: Path) -> str:
    try:
        return str(path.relative_to(REPO_ROOT))
    except ValueError:
        return str(path)


def _resolve_agent(pack_dir: Path, ref: str) -> Path | None:
    if ref.startswith("agents/"):
        candidate = pack_dir / ref
        return candidate if candidate.is_file() else None
    for base in (pack_dir / "agents", CORE_PACK_DIR / "agents"):
        candidate = base / ref
        if candidate.is_file():
            return candidate
    return None


def _resolve_skill(pack_dir: Path, ref: str) -> Path | None:
    if ref.startswith("skills/"):
        candidate = pack_dir / ref
        return candidate if candidate.is_dir() else None
    candidate = SKILLS_DIR / ref
    return candidate if candidate.is_dir() else None


def collect() -> tuple[dict[str, Path], dict[str, Path]]:
    """Return (agents, skills): flat entry name -> source path."""
    agents: dict[str, Path] = {}
    skills: dict[str, Path] = {}
    for pack_dir in sorted(p for p in PACKS_DIR.iterdir() if p.is_dir()):
        if pack_dir.name == TEMPLATE_DIR_NAME:
            continue
        manifest_path = pack_dir / "pack.json"
        if not manifest_path.is_file():
            fail(f"pack {pack_dir.name}/ is missing pack.json")
            continue
        manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
        refs: list[str] = [r for r in (manifest.get("agents") or {}).values() if isinstance(r, str)]
        refs += [r for r in manifest.get("reviewers") or [] if isinstance(r, str)]
        for ref in refs:
            src = _resolve_agent(pack_dir, ref)
            if src is None:
                fail(f"{pack_dir.name}/pack.json: agent '{ref}' resolves nowhere")
                continue
            if src.name in agents and agents[src.name] != src:
                fail(
                    f"agent name conflict for '{src.name}': "
                    f"{_rel(agents[src.name])} vs {_rel(src)}"
                )
            agents[src.name] = src
        for ref in manifest.get("skills") or []:
            src = _resolve_skill(pack_dir, ref)
            if src is None:
                fail(f"{pack_dir.name}/pack.json: skill '{ref}' resolves nowhere")
                continue
            if src.name in skills and skills[src.name] != src:
                fail(
                    f"skill name conflict for '{src.name}': "
                    f"{_rel(skills[src.name])} vs {_rel(src)}"
                )
            skills[src.name] = src
    return agents, skills


def _dir_trees_identical(left: Path, right: Path) -> bool:
    cmp = filecmp.dircmp(left, right)
    if cmp.left_only or cmp.right_only or cmp.diff_files or cmp.funny_files:
        return False
    for sub in cmp.common_dirs:
        if not _dir_trees_identical(left / sub, right / sub):
            return False
    return all(
        filecmp.cmp(left / name, right / name, shallow=False) for name in cmp.common_files
    )


def _sync_dir(dest: Path, sources: dict[str, Path]) -> None:
    """Write mode: make dest contain exactly sources + the marker file."""
    dest.mkdir(parents=True, exist_ok=True)
    wanted = set(sources) | {MARKER_NAME}
    for child in dest.iterdir():
        if child.name not in wanted:
            if child.is_dir() and not child.is_symlink():
                shutil.rmtree(child)
            else:
                child.unlink()
    for name, src in sources.items():
        target = dest / name
        if src.is_dir():
            if target.is_dir():
                shutil.rmtree(target)
            shutil.copytree(src, target)
        else:
            shutil.copy2(src, target)
    (dest / MARKER_NAME).write_text(MARKER_TEXT, encoding="utf-8")


def _check_dir(dest: Path, sources: dict[str, Path]) -> None:
    """Check mode: fail on anything the assembler would change."""
    label = _rel(dest)
    expected = set(sources) | {MARKER_NAME}
    actual = {p.name for p in dest.iterdir()} if dest.is_dir() else set()
    for name in sorted(expected - actual):
        fail(f"{label}: missing '{name}' -- run tools/assemble_flat_layout.py")
    for name in sorted(actual - expected):
        fail(f"{label}: unexpected '{name}' -- not produced from packs/*/")
    for name, src in sources.items():
        target = dest / name
        if not target.exists():
            continue
        if src.is_dir():
            if not target.is_dir() or not _dir_trees_identical(src, target):
                fail(f"{label}: '{name}' differs from pack source -- edit packs/, not the flat layout")
        elif not target.is_file() or not filecmp.cmp(src, target, shallow=False):
            fail(f"{label}: '{name}' differs from pack source -- edit packs/, not the flat layout")
    marker = dest / MARKER_NAME
    if marker.is_file() and marker.read_text(encoding="utf-8") != MARKER_TEXT:
        fail(f"{label}: marker file content changed -- it is managed by the assembler")


def main() -> int:
    parser = argparse.ArgumentParser(description="Assemble the flat layout from packs/*/.")
    parser.add_argument("--check", action="store_true", help="fail if the flat layout is stale")
    args = parser.parse_args()

    agents, skills = collect()
    if failures:
        print(f"\n{len(failures)} assembly error(s).")
        return 1
    print(f"Collected {len(agents)} agents and {len(skills)} skills from packs/*/.")

    targets = [(COPILOT_AGENTS, agents), (GITHUB_AGENTS, agents), (SKILLS_DIR, skills)]
    if args.check:
        for dest, sources in targets:
            _check_dir(dest, sources)
    else:
        for dest, sources in targets:
            _sync_dir(dest, sources)
        print("Flat layout regenerated.")

    if failures:
        print(f"\n{len(failures)} problem(s) found.")
        return 1
    print("OK.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
